version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:latest
    container_name: QoreContainerSQL
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306" # Exposes MySQL port
    networks:
      - qore_network
    volumes:
      - qore_volume:/var/lib/mysql

  # Adminer Database Management Tool
  adminer:
    image: adminer:latest
    container_name: QoreContainerViZ
    ports:
      - "8989:8080" # Exposes Adminer UI port
    networks:
      - qore_network

  # Backend Service
  back:
    restart: on-failure
    container_name: Backend_Container
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8383:8383" # Exposes backend service port
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - qore_network


  # Frontend Service
  client:
    container_name: Frontend_Container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Exposes frontend service port
    volumes:
      - ./client/src:/app/src # Mounts volume for development convenience
    restart: on-failure
    depends_on:
      - back # Depends on the backend service
    environment:
      API_URL: "http://back:8383" # Specifies the API URL for communication with backend


# Volume for persistent data storage
volumes:
  qore_volume:

# Network for inter-service communication
networks:
  qore_network:

