version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - mysql


  client:
    container_name: qoretracking-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      API_URL: "http://back:8086"



volumes:
  mysql_volume:
