// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics": {
            "get": {
                "description": "Get analytics data from Google Analytics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get Analytics Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.AnalyticsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.AggregateMetrics": {
            "type": "object",
            "properties": {
                "averageBounceRate": {
                    "type": "number"
                },
                "averageSessionDuration": {
                    "type": "number"
                },
                "topCityByActiveUsers": {
                    "type": "string"
                },
                "topPageByScreenPageViews": {
                    "type": "string"
                },
                "topRegionByRevenue": {
                    "type": "string"
                },
                "totalActiveUsers": {
                    "type": "integer"
                },
                "totalConversions": {
                    "type": "integer"
                },
                "totalEventCount": {
                    "type": "integer"
                },
                "totalNewUsers": {
                    "type": "integer"
                },
                "totalRevenue": {
                    "type": "number"
                },
                "totalScreenPageViews": {
                    "type": "integer"
                },
                "totalSessions": {
                    "type": "integer"
                }
            }
        },
        "controller.AnalyticsData": {
            "type": "object",
            "properties": {
                "activeUsers": {
                    "type": "integer"
                },
                "averageSessionDuration": {
                    "type": "number"
                },
                "bounceRate": {
                    "type": "number"
                },
                "city": {
                    "type": "string"
                },
                "conversions": {
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                },
                "deviceCategory": {
                    "type": "string"
                },
                "eventCount": {
                    "type": "integer"
                },
                "newUsers": {
                    "type": "integer"
                },
                "pagePath": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "revenue": {
                    "type": "number"
                },
                "screenPageViews": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                }
            }
        },
        "controller.AnalyticsResponse": {
            "type": "object",
            "properties": {
                "aggregateMetrics": {
                    "$ref": "#/definitions/controller.AggregateMetrics"
                },
                "analyticsData": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.AnalyticsData"
                    }
                }
            }
        },
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
